version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./content:/usr/src/app/content
      - ./views:/usr/src/app/views
      - ./public:/usr/src/app/public #Express 経由で /usr/src/app/public/css/styles.css にマッピングされま
      - ./app.js:/usr/src/app/app.js
      - ./package.json:/usr/src/app/package.json
      - ./data/:/usr/src/app/data/
      # - ./package-lock.json:/usr/src/app/package-lock.json
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
